# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_MCC <- function(data, scaleDomain2Spacing = 1.5, curvatureThreshold = 0.3) {
    .Call('_RMCC_R_MCC', PACKAGE = 'RMCC', data, scaleDomain2Spacing, curvatureThreshold)
}

